apolo_app_id: ""  # passed as an input
dbPassword: null
dbSecretName: launchpad-db-secret  # in real app will be f"launchpad-{apolo_app_id}-db-secret"

image:
  repository: "ghcr.io/neuro-inc/launchpad"
  tag: "latest"

replicas: 1
port: 8080

domain: "apps.dev.apolo.us"
netlifyDomain: "launchpad-web-ui-dev-apolo-us.netlify.app"

# apolo specific values
APOLO_PASSED_CONFIG: null
preset_name: cpu-medium
# apolo_app_id: app-id-12345
labels:
  application: launchpad


podLabels: {}
podAnnotations: {}

# application specific values example
LAUNCHPAD_INITIAL_CONFIG: >
  {
      "vllm": {
          "hugging_face_model": {
              "model_hf_name": "microsoft/DialoGPT-medium",
              "hf_token": null
          },
          "preset": {
              "name": "gpu-large"
          },
          "server_extra_args": [
              "--max-model-len=2048",
              "--gpu-memory-utilization=0.9"
          ]
      },
      "postgres": {
          "preset": {
              "name": "cpu-small"
          },
          "pg_bouncer": {
              "preset": {
                  "name": "cpu-small"
              }
          }
      },
      "text-embeddings": {
          "model": {
              "model_hf_name": "BAAI/bge-m3",
              "hf_token": null
          },
          "preset": {
              "name": "gpu-small"
          },
          "server_extra_args": []
      }
  }

postgresql:
  enabled: true
  fullnameOverride: launchpad-db  # in real app will be f"launchpad-{apolo_app_id}-db"
  auth:
    existingSecret: launchpad-db-secret  # # in real app will be f"launchpad-{apolo_app_id}-db-secret"
    username: postgres
    database: postgres
    password: ""   # not used for admin (use existingSecret)
    secretKeys:
      adminPasswordKey: "DB_PASSWORD"
      userPasswordKey: "DB_PASSWORD"
  primary:
    initdb:
      scripts:
        create_dbs.sql: |
          CREATE DATABASE keycloak;
          CREATE DATABASE launchpad;


keycloak:
  defaultRealm: "master" # internal variable
  fullnameOverride: launchpad-keycloak  # in real app will be f"launchpad-{apolo_app_id}-keycloak"
  replicas: 1
  auth:
    adminUser: "admin"
    adminPassword: "Passw0rd!123"  # todo: should be passed as an arg?
  postgresql:
    enabled: false
  externalDatabase:
    user: "postgres"
    database: "keycloak"
    existingSecret: launchpad-db-secret # in real app will be f"launchpad-{apolo_app_id}-db-secret"
    existingSecretHostKey: "DB_HOST"
    existingSecretPasswordKey: "DB_PASSWORD"
  proxy: "edge"
  readinessProbe:
    initialDelaySeconds: 60
    periodSeconds: 30
    failureThreshold: 5
  tolerations:
    - effect: NoSchedule              
      key: platform.neuromation.io/job
      operator: Exists
  service:
    extraLabels: {}
    headless:
      extraLabels: {}