apolo_app_id: ""  # passed as an input
dbPassword: null
dbSecretName: launchpad-db-secret  # in real app will be f"launchpad-{apolo_app_id}-db-secret"
keycloakRealmImportConfigMapName: launchpad-keycloak-realm  # in real app will be f"launchpad-{apolo_app_id}-keycloak-realm"

image:
  repository: "ghcr.io/neuro-inc/launchpad"
  tag: "25.9.18"

replicas: 1
port: 8080

domain: "apps.dev.apolo.us"
netlifyDomain: "launchpad-web-ui-dev-apolo-us.netlify.app"
netlifySecretName: launchpad-secrets

# apolo specific values
APOLO_PASSED_CONFIG: null
preset_name: cpu-medium
# apolo_app_id: app-id-12345
labels:
  application: launchpad


podLabels: {}
podAnnotations: {}

# LAUNCHPAD_ADMIN_PASSWORD: null  # should be set to a secure value in real app

# application specific values example
LAUNCHPAD_INITIAL_CONFIG: >
  {
      "vllm": {
          "hugging_face_model": {
              "model_hf_name": "microsoft/DialoGPT-medium",
              "hf_token": null
          },
          "preset": {
              "name": "gpu-large"
          },
          "server_extra_args": [
              "--max-model-len=2048",
              "--gpu-memory-utilization=0.9"
          ]
      },
      "postgres": {
          "preset": {
              "name": "cpu-small"
          },
          "pg_bouncer": {
              "preset": {
                  "name": "cpu-small"
              }
          }
      },
      "text-embeddings": {
          "model": {
              "model_hf_name": "BAAI/bge-m3",
              "hf_token": null
          },
          "preset": {
              "name": "gpu-small"
          },
          "server_extra_args": []
      }
  }

postgresql:
  global:
    security:
      allowInsecureImages: true
  image:
    repository: bitnamilegacy/postgresql
    tag: 17.5.0-debian-12-r18
  enabled: true
  fullnameOverride: launchpad-db  # in real app will be f"launchpad-{apolo_app_id}-db"
  commonAnnotations:
    argocd.argoproj.io/sync-wave: "0"
  auth:
    existingSecret: launchpad-db-secret  # # in real app will be f"launchpad-{apolo_app_id}-db-secret"
    username: postgres
    database: postgres
    password: ""   # not used for admin (use existingSecret)
    secretKeys:
      adminPasswordKey: "DB_PASSWORD"
      userPasswordKey: "DB_PASSWORD"
  primary:
    initdb:
      scripts:
        create_dbs.sql: |
          CREATE DATABASE keycloak;
          CREATE DATABASE launchpad;
    tolerations:
      - effect: NoSchedule
        key: platform.neuromation.io/job
        operator: Exists
      - effect: NoExecute
        key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        tolerationSeconds: 300
      - effect: NoExecute
        key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        tolerationSeconds: 300
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: platform.neuromation.io/job
                  operator: In
                  values:
                    - "true"

keycloak:
  global:
    security:
      allowInsecureImages: true
  image:
    repository: bitnamilegacy/keycloak
    tag: 26.3.0-debian-12-r0
  defaultRealm: "launchpad" # internal variable
  fullnameOverride: launchpad-keycloak  # in real app will be f"launchpad-{apolo_app_id}-keycloak"
  replicas: 1
  commonAnnotations:
    argocd.argoproj.io/sync-wave: "1"
  auth:
    adminUser: "admin"
    adminPassword: "Passw0rd!123"  # todo: should be passed as an arg?
  postgresql:
    enabled: false
  externalDatabase:
    user: "postgres"
    database: "keycloak"
    existingSecret: launchpad-db-secret # in real app will be f"launchpad-{apolo_app_id}-db-secret"
    existingSecretHostKey: "DB_HOST"
    existingSecretPasswordKey: "DB_PASSWORD"
  proxy: "edge"
  readinessProbe:
    initialDelaySeconds: 120
    periodSeconds: 30
    failureThreshold: 5
  tolerations:
    - effect: NoSchedule
      key: platform.neuromation.io/job
      operator: Exists
  commonLabels:
    service: keycloak
    application: launchpad
  extraVolumes:
    - name: realm-import
      configMap:
        name: launchpad-keycloak-realm  # in real app will be f"launchpad-{apolo_app_id}-keycloak-realm"
        items:
          - key: realm.json
            path: realm.json
  extraVolumeMounts:
    - name: realm-import
      mountPath: /opt/bitnami/keycloak/data/import
      readOnly: true
  initContainers:
    - name: fetch-theme
      image: alpine/git:2.45.2
      imagePullPolicy: IfNotPresent
      command: [ "/bin/sh","-lc" ]
      args:
        - |
          set -euxo pipefail
          git clone --depth 1 --branch "master" "https://github.com/neuro-inc/launchpad.git" /tmp/repo
          mkdir -p "/opt/bitnami/keycloak/themes/apolo"
          cp -R "/tmp/repo/keycloak-theme/apolo/." "/opt/bitnami/keycloak/themes/apolo/"
          # Make sure the KC (1001) user can read the files
          chown -R 1001:0 /opt/bitnami/keycloak/themes
      volumeMounts:
        - name: empty-dir
          mountPath: /opt/bitnami/keycloak/themes
          subPath: app-themes-dir
      securityContext:
        runAsUser: 0
  extraStartupArgs: >-
    --import-realm --spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false
