apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "launchpad.fullname" . }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "launchpad.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "launchpad.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: "ghcr"
      containers:
        - name: launchpad
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command:
            - "python"
            - "-m"
            - "launchpad"
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          ports:
            - containerPort: {{ .Values.port }}
              name: http
              protocol: TCP
          env:
            - name: PORT
              value: {{ .Values.port | quote }}
            - name: DB_HOST
              value: {{ .Values.postgresql.fullnameOverride }}
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.appName }}-db-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              value: "launchpad"
            - name: KEYCLOAK_URL
              value: {{ .Values.keycloakHostPrefix }}
            - name: KEYCLOAK_REALM
              value: {{ .Values.keycloak.defaultRealm }}
