apiVersion: v1
kind: Service
metadata:
  name: {{ include "launchpad.fullname" . }}-client
spec:
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
  type: ExternalName
  sessionAffinity: None
  externalName: {{ .Values.netlifyDomain }}
