apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: launchpad
spec:
  ingressClassName: traefik
  rules:
    - host: {{ include "launchpad.domain" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "launchpad.fullname" $ }}
                port:
                  name: http
