{{- if .Values.netlifySecretName -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "launchpad.name" . }}-netlify-cleanup-job
  namespace: platform
  annotations:
    argocd.argoproj.io/hook: PostDelete
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  labels:
    {{- include "launchpad.labels" . | nindent 4 }}
    service: netlify-cleanup-job
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        {{- include "launchpad.selectorLabels" . | nindent 8 }}
        service: netlify-cleanup-job
    spec:
      restartPolicy: OnFailure
      imagePullSecrets:
        - name: "ghcr"
      containers:
      - name: netlify-domain-remover
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        command: ["python3", "/app/scripts/netlify-cleanup.py"]
        args:
          - "delete"
          - "--site-id"
          - "$(NETLIFY_SITE_ID)"
          - "--domain-alias"
          - "{{ include "launchpad.domain" . }}"
        env:
        - name: NETLIFY_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.netlifySecretName }}
              key: NETLIFY_TOKEN
        - name: NETLIFY_SITE_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Values.netlifySecretName }}
              key: NETLIFY_SITE_ID
{{- end -}}
