apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "launchpad.name" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    {{- include "launchpad.labels" . | nindent 4 }}
    service: launchpad
spec:
  ingressClassName: traefik
  rules:
    - host: {{ include "launchpad.apiDomain" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "launchpad.name" $ }}
                port:
                  name: http
