apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.keycloakProcore.secretName }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  PROCORE_CLIENT_ID: {{ ternary (required "keycloakProcore.clientId is required when keycloakProcore.enabled=true" .Values.keycloakProcore.clientId) "" .Values.keycloakProcore.enabled | quote }}
  PROCORE_CLIENT_SECRET: {{ ternary (required "keycloakProcore.clientSecret is required when keycloakProcore.enabled=true" .Values.keycloakProcore.clientSecret) "" .Values.keycloakProcore.enabled | quote }}
  PROCORE_AUTHORIZATION_URL: {{ .Values.keycloakProcore.authorizationUrl | quote }}
  PROCORE_TOKEN_URL: {{ .Values.keycloakProcore.tokenUrl | quote }}
  PROCORE_ME_URL: {{ .Values.keycloakProcore.meUrl | quote }}
