apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.keycloakProcore.secretName }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  PROCORE_AUTHORIZATION_URL: {{ .Values.keycloakProcore.authorizationUrl | quote }}
  PROCORE_TOKEN_URL: {{ .Values.keycloakProcore.tokenUrl | quote }}
  PROCORE_ME_URL: {{ .Values.keycloakProcore.meUrl | quote }}
